# Generated by Django 4.1.7 on 2023-03-13 09:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_context', ckeditor_uploader.fields.RichTextUploadingField()),
                ('info_context', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User-ID')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='TopTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LigaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200, unique=True)),
                ('games', models.IntegerField()),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('score', models.IntegerField()),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.liga')),
            ],
        ),
        migrations.CreateModel(
            name='LigaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('player', models.CharField(max_length=200)),
                ('games', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.liga')),
            ],
        ),
        migrations.CreateModel(
            name='GameCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.liga')),
            ],
        ),
    ]
